[tool.poetry]
name = "notebook"
version = "0.1.0"
description = ""
authors = ["takeshi0406 <sci.and.eng@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
